"""
The 10 pairs of DNA sequences provided in the assignment PDF
(NLP_O26-Sequence_Alignment_Assignment_v1.pdf), transcribed verbatim from the
PDF's text layer (extracted with pypdf to avoid transcription errors).

Each pair contains "Sequence 1" and "Sequence 2 (Reverse Complement)" exactly
as given in the handout.
"""

DNA_PAIRS = [
    {
        "id": 1,
        "seq1": "GACTTACGCGCCGTAGCACTTCTGTGATAGCTGCGAGGCGTATTGCTACTTGTACGAGATAGGGTCGACTTT"
                "TCGGAGTCGACAGACACTACGATACT",
        "seq2": "AGTATCGTAGTGTCTGTCGACTCCGAAAAGTCGACCCTATCTCGTACAAGTAGCAATACGCCTCGCAGCTAT"
                "CACAGAAGTGCTACGGCGCGTAAGTC",
    },
    {
        "id": 2,
        "seq1": "GTAGTCATTACCCATAGGCGTTTGCTGACTATCGGGAGAGGTACGTACGTGATACGACTGTCGATCGCTCGT"
                "AGATCAAGATACTCAGCGTGCTGTC",
        "seq2": "GACAGCACGCTGAGTATCTTGATCTACGATCGACAGTCGTATCACGTACGTACCTCTCCCGATAGTCAGCAA"
                "ACGCCTATGGGTAATGACTAC",
    },
    {
        "id": 3,
        "seq1": "CTGCATACCGACAAACGTGTGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCACATGC"
                "ATACGTGCGTGTCTACGTACGT",
        "seq2": "ACGTACGTCTACGCACGTATGCATGTGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC"
                "ACACGTTTGTCGGTATGCAG",
    },
    {
        "id": 4,
        "seq1": "GGATGCGACTAGGAGTCGAGTGTCGATTCTATAGCGATAGCGAGTAGCGACTAGTCACTGTACTGTAGCAT"
                "AGCGATACGAGCATAGCATAGCA",
        "seq2": "TGCTATGCTATGCTCGTATCGCTATGCTACAGTGACTAGTCGCTACTCGCTATCGCTATAGAATCGACACTC"
                "GACTCCTAGTCGCATCC",
    },
    {
        "id": 5,
        "seq1": "TCGATCGTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCT"
                "AGCTAGCTAGCTAGCTAGCTAGC",
        "seq2": "GCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"
                "GCTACGATCGAC",
    },
    {
        "id": 6,
        "seq1": "ATGCGTATACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"
                "ACGTACGTACGTACGTACG",
        "seq2": "CGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTA"
                "TACGCAT",
    },
    {
        "id": 7,
        "seq1": "TTAAATTATATATATACGCGCGCGCGACACACACACACTGATCTATACGCGCGCGCGCGATAGCGATAGCGA"
                "TCGATCGCGCTATATATATA",
        "seq2": "TATATATAGCGCGATCGATCGCTATCGCTATCGCGCGCGCGTATAGATCAGTGTGTGTGTGTCGCGCGCGCG"
                "TATATATATAATTTAA",
    },
    {
        "id": 8,
        "seq1": "CTACTGAGTCGTAGCTAGCGAGTCGAGTGCGTGCATGCATGCATGCATGCATGCATGCATGCATGCATGCAT"
                "GCATGCATGCATGCATGC",
        "seq2": "GCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCACGACTCGACTCGCTAGC"
                "TACGACTCAGTAG",
    },
    {
        "id": 9,
        "seq1": "GCATGCGACTTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"
                "GCTAGCTAGCTAGCTAGCATGC",
        "seq2": "GCATGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTA"
                "GCTAGCTAAGTCGCATGC",
    },
    {
        "id": 10,
        "seq1": "CGCGATAGCGATAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCT"
                "AGCTAGCTAGCTAGCTAGCTAG",
        "seq2": "CTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAG"
                "CTATCGCTATCGCG",
    },
]


def get_pair(pair_id: int) -> dict:
    """Return the pair dict {id, seq1, seq2} for the given 1-based pair id."""
    for pair in DNA_PAIRS:
        if pair["id"] == pair_id:
            return pair
    raise KeyError(f"No pair with id={pair_id}")
